INCATools/ubergraph

ubergraph-axioms.ofn
Hardcoding this for now, since Upheno is undergoing change.
=> Connect HP phenotype to Upheno.

Makefile
See https://github.com/NCATSTranslator/opposites/issues/6.
=> Add Translator opposites.

Makefile, sparql/kgx-edges.rq, sparql/kgx-nodes.rq
Still need to compact prefixes in the TSV output.
=> Add KGX output. Update biolink version.

Jenkinsfile
=> Build weekly.

Makefile
=> Add PO and PPO.

sparql/map2slim.rq
Fixes #52 
David requested a API to create subset with given term list, lists are supported with grlc yet. We decided go with mapping a single term rather than a term list for now.
=> GRLC query - map2slim 

README.md, ontologies.txt
=> Remove EFO.

Makefile, non-base-ontologies.txt
=> Add FOODON.

Makefile
=> Create N-quads dump

Dockerfile, Makefile
=> Output integer-based graph for download.

sparql/obsolete_replaced-by_term.rq, sparql/obsolete_replaced-by_terms_by_ontology.rq
=> Add GRLC endpoint for replaced_by annotations

Makefile, ontologies.txt
=> Add PCO, TO, PECO.

ic.dl
=> Change IC score to count all incoming relations.

Makefile
=> Use OWL for PRO.

Makefile
=> Include MRO.

ontologies.txt
=> Add ORCIDIO ontology.

Makefile
=> Load OBO registry prefixes declarations.

ontologies.txt
It is an integral part of phenotype definitions as well
=> Add NBO to Ubergraph

ci/catalog-v001.xml, ci/test-merged.ofn, ci/test-merged.sh
=> Remove RO other_import from test.

ontologies.txt
=> Add Vertebrate Breed Ontology

ontologies.txt
See https://github.com/OBOFoundry/COB/issues/297.
=> Load cob.owl rather than cob-to-external
